server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blog.cytrdvvkoauk.ap-northeast-2.rds.amazonaws.com:3307/blogAWS?serverTimezone=Asia/Seoul
    username: hong
    password: hong1234
      
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  #JPA가 사용하는 기본 넘버링을 사용하지 않겠다!
    #show-sql: true                                           # sysout(sql);
    #properties:
      #hibernate.format_sql: true                # 줄바꿔서 sysout()해줌

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  application:
    name: user-service
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 581936500239-9q9mgjiq03ciaou7m9aheios1211ncqk.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
          facebook:
            client-id: 1544989799316085
            client-secret: 7e632ac425a3b510a240b266594fa4b0
            scope:
            - email
            - public_profile
           
          naver:
            client-id: vEDDC8YKf4GFCJHAMiUM
            client-secret: VENilxKBHr
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
          
        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 return 해줌
              
hong:
  key: hong1234